### ISSUE TITLE
Publish to Sonatype central?

### ISSUE THREAD

**Issue by mahe-ymc** [slamdata/fs2-ssh#97]
Is there a chance to get most current version published to Sonatype central? Older versions are available: https://central.sonatype.com/search?smo=true&q=fs2-ssh

**Comment by wemrysi** [comment]
Hello, no we won't be publishing to sonatype as we switched to publishing to github packages as an org years ago.

Here's some info on how to configure github packages in maven, https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-to-github-packages .

If you're using `sbt`, you might be interested in the [sbt-github-packages](https://github.com/djspiewak/sbt-github-packages#resolvers) plugin, which makes it convenient to depend on artifacts published to github packages.
